name: "Build and Deploy to Firebase and Testflight"

on:
  workflow_dispatch:

jobs:
  build-apk-and-deploy-to-firebase:
    name: "Build APK and Deploy to Firebase"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.x'

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: |
          VERSION=$(grep -i -e "version: " pubspec.yaml | awk '{print $2}')
          VERSION_CODE=$(echo "${GITHUB_RUN_NUMBER}000" | cut -d '.' -f 1)
          echo "VERSION=$VERSION"
          echo "VERSION_CODE=$VERSION_CODE"
          flutter build apk --release --build-name=$VERSION --build-number=$VERSION_CODE

      - name: Deploy to Firebase
        run: |
          cd android
          bundle install
          bundle exec fastlane deploy_to_firebase

  build-ipa-and-deploy-to-testflight:
    name: "Build IPA and Deploy to Testflight"
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.x'

      - name: Get dependencies
        run: flutter pub get

      - name: Build IPA
        run: |
          VERSION=$(grep -i -e "version: " pubspec.yaml | awk '{print $2}')
          BUILD_NUMBER=$(expr ${GITHUB_RUN_NUMBER} + 1)
          echo "VERSION=$VERSION"
          echo "BUILD_NUMBER=$BUILD_NUMBER"
          flutter build ios --release --build-name=$VERSION --build-number=$BUILD_NUMBER

      - name: Deploy to Testflight
        run: |
          cd ios
          bundle install
          bundle exec fastlane deploy_to_testflight
